### ISSUE TITLE
mac 版无法导入主题

### ISSUE THREAD

**Issue by xream** [maotoumao/MusicFreeThemePacks#2]
版本 0.0.2
预期: 选择文件夹后点击安装 将导入主题
现象: 选择文件夹后点击安装 会进入下一级文件目录 此时安装按钮不可点击

**Comment by xk756** [comment]
+1

**Comment by maotoumao** [comment]
抱歉～ 0.0.2版本更新了主题包的安装逻辑；

之前是安装文件夹，但是文件夹只支持单选，无法批量安装；
改动后主题包为.zip或.mftheme文件，可以批量安装

下载这个文件⬇️然后解压，安装里面的mftheme文件就可以了～  文档我更新一下～
https://wwwzb.lanzoue.com/i9eDT1dowk7i
