### ISSUE TITLE
手机使用

### ISSUE THREAD

**Issue by maonianccw0** [maotoumao/MusicFreeThemePacks#8]
手机的怎么使用，下载完后没有安装按键，用了mt管理器也不知道把文件移动到哪里

**Comment by maotoumao** [comment]
主题包目前只支持电脑版

**Comment by maonianccw0** [comment]
> 主题包目前只支持电脑版

酱紫啊，好吧谢谢，还有能不能出个酷狗的插件，真的找不到，网易云跟QQ的用的少，都在酷狗，插件找不到.js.json研究了两天不会
