### ISSUE TITLE
MusicFree 桌面自用主题包

### ISSUE THREAD

**Issue by akFace** [maotoumao/MusicFreeThemePacks#9]
喜欢的可以自行下载使用哦
纯白色的 https://github.com/akFace/MusicFreeTheme

**Comment by maotoumao** [comment]
很不错👍  我可以把这个主题的链接发在公众号嘛（下次发推送的时候）

**Comment by akFace** [comment]
> 很不错👍 我可以把这个主题的链接发在公众号嘛（下次发推送的时候）

可以的
